In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv("../data_files/sentences.csv")
df.head()

,defendant,sentence,Name,Name (sortable),Aliases,Gender,Races,Jurisdiction,State Abbreviation,Sub Jurisdiction,County and State,Region,Year,Multi-sentence identifier,Outcome of Sentence,Current Case Status
0,5303,5501,Reno [No Last Name],[no last name] reno,Harold R. Memro,Male,White,California,CA,Los Angeles County,"Los Angeles County, California",West,1979.0,1.1,Resentenced to Death,Active Death Sentence
1,5303,5502,Reno [No Last Name],[no last name] reno,Harold R. Memro,Male,White,California,CA,Los Angeles County,"Los Angeles County, California",West,1987.0,1.2,Active Death Sentence,Active Death Sentence
2,5304,5503,Joe Henry Abbott,abbott joe,NaN,Male,Black,California,CA,San Bernardino County,"San Bernardino County, California",West,2006.0,NaN,Died on Death Row,Died on Death Row
3,5305,5504,Dane Abdool,abdool dane,NaN,Male,White,Florida,FL,Orange County,"Orange County, Florida",South,2008.0,NaN,Grant of Relief (Retrial/Resentencing Pending),Grant of Relief (Retrial/Resentencing Pending)
4,6433,7392,Jalil Abdul-Kabir,abdul-kabir jalil,Ted Calvin Cole,Male,White,Texas,TX,Tom Green County,"Tom Green County, Texas",South,1988.0,NaN,Resentenced to Life or Less,Resentenced to Life or Less

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9940 entries, 0 to 9939
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   defendant                  9940 non-null   int64
 1   sentence                   9940 non-null   int64
 2   Name                       9940 non-null   str
 3   Name (sortable)            9940 non-null   str
 4   Aliases                    304 non-null    str
 5   Gender                     9939 non-null   str
 6   Races                      9935 non-null   str
 7   Jurisdiction               9940 non-null   str
 8   State Abbreviation         9831 non-null   str
 9   Sub Jurisdiction           9938 non-null   str
 10  County and State           9940 non-null   str
 11  Region                     9919 non-null   str
 12  Year                       9931 non-null   float64
 13  Multi-sentence identifier  1890 non-null   str
 14  Outcome of Sentence        9940 non-null   str
 15  Current Case Status        9940 non-null   str
dtypes: float64(1), int64(2), str(13)
memory usage: 1.2 MB

In [11]:
df = df.sort_values(by='Year')
df.head()

,defendant,sentence,Name,Name (sortable),Aliases,Gender,Races,Jurisdiction,State Abbreviation,Sub Jurisdiction,County and State,Region,Year,Multi-sentence identifier,Outcome of Sentence,Current Case Status
9273,11400,15805,Junior Lee Washington,washington junior,NaN,Male,Black,North Carolina,NC,Hoke County,"Hoke County, North Carolina",South,1972.0,NaN,Resentenced to Life or Less,Resentenced to Life or Less
8605,10943,15058,Vernon Charles Talbert,talbert vernon,NaN,Male,White,North Carolina,NC,Rowan County,"Rowan County, North Carolina",South,1972.0,NaN,Resentenced to Life or Less,Resentenced to Life or Less
9291,11414,15829,Harold Legusta Watkins,watkins harold,NaN,Male,Black,North Carolina,NC,Richmond County,"Richmond County, North Carolina",South,1972.0,NaN,Resentenced to Life or Less,Resentenced to Life or Less
710,5769,6259,Johnny James Blackmon,blackmon johnny,NaN,Male,Black,North Carolina,NC,Union County,"Union County, North Carolina",South,1972.0,NaN,Resentenced to Life or Less,Resentenced to Life or Less
2409,6890,8162,Howard Douglas,douglas howard,NaN,Male,White,Florida,FL,Polk County,"Polk County, Florida",South,1973.0,1.1,Resentenced to Death,Resentenced to Life or Less