In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
df = pd.read_csv("../data_files/executions.csv")
df.head()

# use concat to combine datasets, deal with null values somehow

,First Name,Last Name,Middle Name(s),Suffix,Race,Sex,Age,Foreign National,Juvenile,Federal,...,Number of Asian Male Victims,Number of Native American Male Victims,Number of Other Race Male Victims,Number of White Female Victims,Number of Black Female Victims,Number of Latino Female Victims,Number of Asian Female Victims,Number of American Indian or Alaska Native Female Victims,Number of Other Race Female Victims,Victim Races Includes White
0,Gary,Gilmore,Mark,NaN,White,Male,36,No,No,No,...,0,0,0,0,0,0,0,0,0,Yes
1,John,Spenkelink,NaN,NaN,White,Male,30,No,No,No,...,0,0,0,0,0,0,0,0,0,Yes
2,Jesse,Bishop,NaN,NaN,White,Male,46,No,No,No,...,0,0,0,0,0,0,0,0,0,Yes
3,Steven,Judy,Timothy,NaN,White,Male,24,No,No,No,...,0,0,0,2,0,0,0,0,0,Yes
4,Frank,Coppola,NaN,NaN,White,Male,38,No,No,No,...,0,0,0,0,0,0,0,0,0,Yes

In [ ]:
df.columns
# can I consolidate the victim columns?

Index(['First Name', 'Last Name', 'Middle Name(s)', 'Suffix', 'Race', 'Sex',
       'Age', 'Foreign National', 'Juvenile', 'Federal', 'Region', 'Country',
       'State', 'County', 'Execution Date', 'Method', 'Victims',
       'Victim Races', 'Number of Victims', 'Number of Male Victims',
       'Number of Female Victims', 'Number of White Male Victims',
       'Number of Black Male Victims', 'Number of Latino Male Victims',
       'Number of Asian Male Victims',
       'Number of Native American Male Victims',
       'Number of Other Race Male Victims', 'Number of White Female Victims',
       'Number of Black Female Victims', 'Number of Latino Female Victims',
       'Number of Asian Female Victims',
       'Number of American Indian or Alaska Native Female Victims',
       'Number of Other Race Female Victims', 'Victim Races Includes White'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1661 entries, 0 to 1660
Data columns (total 34 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   First Name                                                 1661 non-null   str
 1   Last Name                                                  1661 non-null   str
 2   Middle Name(s)                                             1022 non-null   str
 3   Suffix                                                     109 non-null    str
 4   Race                                                       1659 non-null   str
 5   Sex                                                        1661 non-null   str
 6   Age                                                        1661 non-null   int64
 7   Foreign National                                           1661 non-null   str
 8   Juvenile                                                   1661 non-null   str
 9   Federal                                                    1661 non-null   str
 10  Region                                                     1661 non-null   str
 11  Country                                                    1661 non-null   str
 12  State                                                      1661 non-null   str
 13  County                                                     1659 non-null   str
 14  Execution Date                                             1661 non-null   str
 15  Method                                                     1661 non-null   str
 16  Victims                                                    1661 non-null   str
 17  Victim Races                                               1660 non-null   str
 18  Number of Victims                                          1661 non-null   int64
 19  Number of Male Victims                                     1661 non-null   int64
 20  Number of Female Victims                                   1661 non-null   int64
 21  Number of White Male Victims                               1661 non-null   int64
 22  Number of Black Male Victims                               1661 non-null   int64
 23  Number of Latino Male Victims                              1661 non-null   int64
 24  Number of Asian Male Victims                               1661 non-null   int64
 25  Number of Native American Male Victims                     1661 non-null   int64
 26  Number of Other Race Male Victims                          1661 non-null   int64
 27  Number of White Female Victims                             1661 non-null   int64
 28  Number of Black Female Victims                             1661 non-null   int64
 29  Number of Latino Female Victims                            1661 non-null   int64
 30  Number of Asian Female Victims                             1661 non-null   int64
 31  Number of American Indian or Alaska Native Female Victims  1661 non-null   int64
 32  Number of Other Race Female Victims                        1661 non-null   int64
 33  Victim Races Includes White                                1661 non-null   str
dtypes: int64(16), str(18)
memory usage: 441.3 KB

In [9]:
df.describe(include='all')

,First Name,Last Name,Middle Name(s),Suffix,Race,Sex,Age,Foreign National,Juvenile,Federal,...,Number of Asian Male Victims,Number of Native American Male Victims,Number of Other Race Male Victims,Number of White Female Victims,Number of Black Female Victims,Number of Latino Female Victims,Number of Asian Female Victims,Number of American Indian or Alaska Native Female Victims,Number of Other Race Female Victims,Victim Races Includes White
count,1661,1661,1022,109,1659,1661,1661.000000,1661,1661,1661,...,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661
unique,500,1126,323,5,6,2,NaN,2,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,Robert,Johnson,Lee,Jr.,White,Male,NaN,No,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
freq,70,29,76,87,931,1643,NaN,1627,1639,1645,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1300
mean,NaN,NaN,NaN,NaN,NaN,NaN,43.029500,NaN,NaN,NaN,...,0.015653,0.001806,0.001806,0.550271,0.109573,0.037327,0.007827,0.003010,0.001204,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,10.319812,NaN,NaN,NaN,...,0.133518,0.054852,0.042473,0.725214,0.410743,0.229832,0.106698,0.064868,0.034690,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,35.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,42.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,NaN,NaN,NaN,...,2.000000,2.000000,1.000000,10.000000,5.000000,4.000000,2.000000,2.000000,1.000000,NaN

In [10]:
df.describe()

,Age,Number of Victims,Number of Male Victims,Number of Female Victims,Number of White Male Victims,Number of Black Male Victims,Number of Latino Male Victims,Number of Asian Male Victims,Number of Native American Male Victims,Number of Other Race Male Victims,Number of White Female Victims,Number of Black Female Victims,Number of Latino Female Victims,Number of Asian Female Victims,Number of American Indian or Alaska Native Female Victims,Number of Other Race Female Victims
count,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000,1661.000000
mean,43.029500,1.443107,0.733895,0.709211,0.535822,0.112583,0.065021,0.015653,0.001806,0.001806,0.550271,0.109573,0.037327,0.007827,0.003010,0.001204
std,10.319812,1.005968,0.893882,0.770131,0.800271,0.456510,0.309467,0.133518,0.054852,0.042473,0.725214,0.410743,0.229832,0.106698,0.064868,0.034690
min,22.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,42.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,50.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,83.000000,16.000000,12.000000,10.000000,12.000000,6.000000,5.000000,2.000000,2.000000,1.000000,10.000000,5.000000,4.000000,2.000000,2.000000,1.000000

In [11]:
df.value_counts()

First Name  Last Name   Middle Name(s)  Suffix  Race   Sex   Age  Foreign National  Juvenile  Federal  Region   Country        State           County              Execution Date  Method            Victims                                       Victim Races  Number of Victims  Number of Male Victims  Number of Female Victims  Number of White Male Victims  Number of Black Male Victims  Number of Latino Male Victims  Number of Asian Male Victims  Number of Native American Male Victims  Number of Other Race Male Victims  Number of White Female Victims  Number of Black Female Victims  Number of Latino Female Victims  Number of Asian Female Victims  Number of American Indian or Alaska Native Female Victims  Number of Other Race Female Victims  Victim Races Includes White
John        Gardner     Sterling        Jr.     White  Male  34   No                No        No       South    United States  North Carolina  Forsyth County      10/23/1992      Lethal Injection  1 White Female, 1 White Male                  White         2                  1                       1                         1                             0                             0                              0                             0                                       0                                  1                               0                               0                                0                               0                                                          0                                    Yes                            1
Freddie     Webb        Lee             Sr.     Black  Male  33   No                No        No       South    United States  Texas           Nueces County       03/31/1994      Lethal Injection  1 Latino/a Male                               Latino/a      1                  1                       0                         0                             0                             1                              0                             0                                       0                                  0                               0                               0                                0                               0                                                          0                                    No                             1
Anthony     LaRette     Joe             Jr.     White  Male  44   No                No        No       Midwest  United States  Missouri        Warren County       11/29/1995      Lethal Injection  1 White Female                                White         1                  0                       1                         0                             0                             0                              0                             0                                       0                                  1                               0                               0                                0                               0                                                          0                                    Yes                            1
Robert      O'Neal      Earl            Jr.     White  Male  44   No                No        No       Midwest  United States  Missouri        Butler County       12/06/1995      Lethal Injection  1 Black Male                                  Black         1                  1                       0                         0                             1                             0                              0                             0                                       0                                  0                               0                               0                                0                               0                                                          0                                    No                             1
James       Clark       B.              Jr.     White  Male  39   No                No        No       South    United States  Delaware        New Castle County   04/19/1996      Lethal Injection  1 White Female, 1 White Male                  White         2                  1                       1                         1                             0                             0                              0                             0                                       0                                  1                               0                               0                                0                               0                                                          0                                    Yes                            1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ..
Thomas      Loden       Edwin           Jr.     White  Male  58   No                No        No       South    United States  Mississippi     Itawamba County     12/14/2022      Lethal Injection  1 White Female                                White         1                  0                       1                         0                             0                             0                              0                             0                                       0                                  1                               0                               0                                0                               0                                                          0                                    Yes                            1
Richard     Rojem       Norman          Jr.     White  Male  66   No                No        No       South    United States  Oklahoma        Washita County      06/27/2024      Lethal Injection  3 White Females                               White         3                  0                       3                         0                             0                             0                              0                             0                                       0                                  3                               0                               0                                0                               0                                                          0                                    Yes                            1
Jessie      Hoffman     Dean            Jr.     Black  Male  46   No                No        No       South    United States  Louisiana       St. Tammany Parish  03/18/2025      Gas               1 White Female                                White         1                  0                       1                         0                             0                             0                              0                             0                                       0                                  1                               0                               0                                0                               0                                                          0                                    Yes                            1
Edward      Zakrzewski  J.              II      White  Male  60   No                No        No       South    United States  Florida         Okaloosa County     07/31/2025      Lethal Injection  1 Asian Female, 1 White Male, 1 White Female  Asian, White  3                  1                       2                         1                             0                             0                              1                             0                                       0                                  1                               0                               0                                2                               0                                                          0                                    Yes                            1
Norman      Grim        Mearle          Jr.     White  Male  65   No                No        No       South    United States  Florida         Santa Rosa County   10/28/2025      Lethal Injection  1 White Female                                White         1                  0                       1                         0                             0                             0                              0                             0                                       0                                  1                               0                               0                                0                               0                                                          0                                    Yes                            1
Name: count, Length: 64, dtype: int64

In [12]:
df['Foreign National'].value_counts()

Foreign National
No     1627
Yes      34
Name: count, dtype: int64

In [13]:
df['Juvenile'].value_counts()

Juvenile
No     1639
Yes      22
Name: count, dtype: int64

In [20]:
df[df['Juvenile'] == 'Yes'][['Race', 'Age', 'Sex', 'Region', 'Victims']]

         Race  Age   Sex   Region                        Victims
47      White   28  Male    South                   1 White Male
50      White   25  Male    South   1 White Female, 1 White Male
56      White   24  Male    South                2 White Females
127     Black   30  Male    South                   1 White Male
160     White   28  Male    South                 1 White Female
206     Black   31  Male    South                   1 White Male
208     Black   29  Male  Midwest                 1 Black Female
213  Latino/a   26  Male    South                1 Latino/a Male
223     White   33  Male    South                   1 White Male
454     White   38  Male    South                 1 White Female
459     Black   34  Male    South              1 Latino/a Female
484     Black   24  Male    South                 1 Black Female
511     White   29  Male    South  1 White Female, 2 White Males
600     White   26  Male    South                  2 White Males
603     White   23  Male    South                 1 White Female
608     Black   27  Male    South                 1 White Female
647     Black   36  Male    South                   1 White Male
736     Black   33  Male    South                   1 White Male
778     Black   25  Male    South                   1 White Male
788     Black   25  Male    South                   1 White Male
794     Black   24  Male    South                3 Black Females
842     White   32  Male    South   1 White Male, 1 White Female

In [15]:
df['Method'].value_counts()

Method
Lethal Injection    1470
Electrocution        163
Gas                   19
Firing Squad           6
Hanging                3
Name: count, dtype: int64

In [21]:
df['Race'].value_counts()

Race
White                               931
Black                               563
Latino/a                            135
American Indian or Alaska Native     21
Asian                                 6
Other Race                            3
Name: count, dtype: int64